version: '3.8'

services:
  backend:
    build: .
    command: gunicorn greengo.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - 8000
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgres/data/
    environment:
      - POSTGRES_USER=greengo
      - POSTGRES_PASSWORD=greengo
      - POSTGRESS_DB=greengo

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static
    ports:
      - 81:80
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume: