# Generated by Django 3.2.6 on 2021-08-24 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dispatcher',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.invoicestatus'),
        ),
        migrations.AlterField(
            model_name='invoicestatus',
            name='color',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='invoicestatus',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='owneroperator',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
