# Generated by Django 3.2.6 on 2021-08-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210824_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='pdf/')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='documents',
            field=models.ManyToManyField(to='home.PdfFile'),
        ),
    ]
