# Generated by Django 3.2.6 on 2021-08-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210825_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
