# Generated by Django 3.2.6 on 2021-09-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_documents_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='trailer_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='documents',
            name='type',
            field=models.IntegerField(choices=[(1, 'Documents'), (2, 'Drivers Aplications'), (3, 'Existiong Trucks Docs')], default=1),
        ),
    ]
