# Generated by Django 3.2.6 on 2022-11-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20211005_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdffile',
            name='company',
        ),
        migrations.AddField(
            model_name='driver',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='driverstatus',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='dh',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='milage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
